# Generated by Django 5.2.9 on 2026-01-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_limit_minutes', models.IntegerField(default=5, help_text='Duration of the quiz in minutes')),
            ],
            options={
                'verbose_name_plural': 'Quiz Settings',
            },
        ),
    ]
