# Generated by Django 5.2.9 on 2026-02-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_category_quizsettings_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_limit_minutes',
            field=models.IntegerField(default=5, help_text='Duration of the quiz for this category in minutes'),
        ),
    ]
