# Generated by Django 5.2.9 on 2026-02-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_category_time_limit_minutes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizSettings',
        ),
    ]
